### ISSUE TITLE
node_LSTM.json in G_preparation.py missing

### ISSUE THREAD

**Issue by schelian** [lyufj/CS229_Project#1]
Hi @lyufj , looks like one should first download amazon0302.txt and remove its header, then run link_prep.py, then G_preparation.py.  However, that is expecting a file called node_LSTM.json to exist.

How do you make that file?  If possible please also provide the steps needed to generate all the files needed for the network (e.g., first link_prep.py, then G_preparation.py, then ... ).

**Comment by lyufj** [comment]
Hi Suhas,

The all of the node.json files should be prepared by running node_prep.py.

Sorry, I didn't write the whole process for data preparation. I will do it when I get time.

Thanks,
Fengjiao
